apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: pod-a
  namespace: ggckad-s2 
spec:
  securityContext:
    runAsUser: 3000
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: container-a
    securityContext:
      runAsUser: 1000
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: container-b
    securityContext:
      runAsUser: 2000
