apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    run: app1
spec:
  nodeName: node-1
  containers:
  - image: nginx
    name: lfccncf/arg-output
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
    command: ["-Q", "--dep", "test"]
  volumes:
  - name: test-volume
    hostPath:
      path: /data/html
      type: Directory
