apiVersion: v1
kind: Pod
metadata:
  name: question-four
  namespace: ggckad-s4
spec:
  containers:
  - name: liveness-readiness
    image: kubegoldenguide/question-thirteen
    ports:
    - containerPort: 80
    livenessProbe:
      initialDelaySeconds: 16
      periodSeconds: 10
      httpGet:
        path: /health
        port: 8080
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /started
        port: 8080
